version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

networks:
  default:
    name: wheelsonrent-network
